/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemasolar;

/**
 *
 * @author Giancarlos
 */
public class SistemaSolar extends javax.swing.JFrame {

    /**
     * Creates new form SistemaSolar
     */
    public SistemaSolar() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalir1 = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        Titulo = new javax.swing.JLabel();
        btnjupiter = new javax.swing.JButton();
        btnmercurio = new javax.swing.JButton();
        btnvenus = new javax.swing.JButton();
        btntierra = new javax.swing.JButton();
        btnmarte = new javax.swing.JButton();
        btnsaturno = new javax.swing.JButton();
        btnurano = new javax.swing.JButton();
        btnNeptuno = new javax.swing.JButton();
        btnsol = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISTEMA SOLAR ");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalir1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnSalir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes2/boton.png"))); // NOI18N
        btnSalir1.setBorder(null);
        btnSalir1.setBorderPainted(false);
        btnSalir1.setContentAreaFilled(false);
        btnSalir1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 40, 100, 100));

        btnSalir.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes2/atras.png"))); // NOI18N
        btnSalir.setBorder(null);
        btnSalir.setBorderPainted(false);
        btnSalir.setContentAreaFilled(false);
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 100, 100));

        Titulo.setFont(new java.awt.Font("Dylan Gothic", 1, 70)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Los planetas");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1370, 90));

        btnjupiter.setBorder(null);
        btnjupiter.setContentAreaFilled(false);
        btnjupiter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnjupiter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnjupiterActionPerformed(evt);
            }
        });
        getContentPane().add(btnjupiter, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 290, 200, 200));

        btnmercurio.setBorder(null);
        btnmercurio.setContentAreaFilled(false);
        btnmercurio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnmercurio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmercurioActionPerformed(evt);
            }
        });
        getContentPane().add(btnmercurio, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 50, 40));

        btnvenus.setBorder(null);
        btnvenus.setContentAreaFilled(false);
        btnvenus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnvenus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvenusActionPerformed(evt);
            }
        });
        getContentPane().add(btnvenus, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 100, 100));

        btntierra.setBorder(null);
        btntierra.setContentAreaFilled(false);
        btntierra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btntierra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntierraActionPerformed(evt);
            }
        });
        getContentPane().add(btntierra, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, 110, 100));

        btnmarte.setBorder(null);
        btnmarte.setContentAreaFilled(false);
        btnmarte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnmarte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmarteActionPerformed(evt);
            }
        });
        getContentPane().add(btnmarte, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 340, 90, 100));

        btnsaturno.setBorder(null);
        btnsaturno.setContentAreaFilled(false);
        btnsaturno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsaturno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaturnoActionPerformed(evt);
            }
        });
        getContentPane().add(btnsaturno, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 310, 170, 160));

        btnurano.setBorder(null);
        btnurano.setContentAreaFilled(false);
        btnurano.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnurano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnuranoActionPerformed(evt);
            }
        });
        getContentPane().add(btnurano, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 330, 120, 120));

        btnNeptuno.setBorder(null);
        btnNeptuno.setContentAreaFilled(false);
        btnNeptuno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNeptuno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNeptunoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNeptuno, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 340, 110, 100));

        btnsol.setBorder(null);
        btnsol.setContentAreaFilled(false);
        btnsol.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsolActionPerformed(evt);
            }
        });
        getContentPane().add(btnsol, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 170, 210));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo-español.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnjupiterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnjupiterActionPerformed
        Jupiter j= new Jupiter();
        j.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnjupiterActionPerformed

    private void btnmercurioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmercurioActionPerformed
        Mercurio m = new Mercurio();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnmercurioActionPerformed

    private void btntierraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntierraActionPerformed
        Tierra t = new Tierra();
        t.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btntierraActionPerformed

    private void btnmarteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmarteActionPerformed
        Marte ma = new Marte();
        ma.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnmarteActionPerformed

    private void btnsaturnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaturnoActionPerformed
       Saturno s = new Saturno();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnsaturnoActionPerformed

    private void btnuranoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnuranoActionPerformed
        Urano u = new Urano();
        u.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnuranoActionPerformed

    private void btnNeptunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNeptunoActionPerformed
        Neptuno n = new Neptuno();
        n.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnNeptunoActionPerformed

    private void btnsolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsolActionPerformed
       Sol sol = new Sol();
        sol.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnsolActionPerformed

    private void btnvenusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvenusActionPerformed
        Venus v = new Venus();
        v.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnvenusActionPerformed

    private void btnSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir1ActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalir1ActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        Astronauta as = new Astronauta();
        as.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SistemaSolar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SistemaSolar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SistemaSolar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SistemaSolar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SistemaSolar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton btnNeptuno;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSalir1;
    private javax.swing.JButton btnjupiter;
    private javax.swing.JButton btnmarte;
    private javax.swing.JButton btnmercurio;
    private javax.swing.JButton btnsaturno;
    private javax.swing.JButton btnsol;
    private javax.swing.JButton btntierra;
    private javax.swing.JButton btnurano;
    private javax.swing.JButton btnvenus;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
